### ISSUE TITLE
css : specify icon selectors

### ISSUE THREAD

**Issue by ak4t0sh** [blindsidenetworks/moodle-mod_bigbluebuttonbn#107]
In commit c509ff8 you have added a new "bigbluebutton" font and used 
`[class^="icon-"]:before, [class*=" icon-"]:before` ([styles.css#L16](https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/blob/41e2e7abc4a2c29b281be6f984608db0fc7c1919/styles.css#L16)) as selector to apply it.  
  
But some themes use "icon-" syntax to display icons too. 
For example [theme_moove](https://moodle.org/plugins/theme_moove) use `icon-bell` for notifications and `icon-envelope` for messages.  
As your selectors target classes starting (`^=`) or containing (`*=`) "icon-" browser try to apply your font on `icon-bell` and `icon-envelope` which does not exist in it and so appear as broken.

You  should specify your selectors to prevent such collisions :)

**Comment by danielneis** [comment]
adding my two cents: moodle adds classes for which module is responsible for the page being rendered, so we can use things like `#mod-bigbluebuttonbn` selector at some level to restrict this font change to pages withing the plugin and also to `#main-content` element inside de page to avoid conflics with themes headers, footers and other content

**Comment by jfederico** [comment]
Good points. Both. We'll check it out.
Thanks

**Comment by jfederico** [comment]
Merged #113
