### ISSUE TITLE
Missing Language Strings

### ISSUE THREAD

**Issue by mkpelletier** [blindsidenetworks/moodle-mod_bigbluebuttonbn#111]
In the latest version of mod_bigbluebutton (2.2.10) the language strings for [[view_recording_format_podcast]] and [[view_recording_format_screenshare]] appear to be missing from the language file.

**Comment by jfederico** [comment]
Yes, good point. Thanks for the report. Although is not only 2.2.10 I am afraid. It is any version using BBB 2.0 or later.

I'll make sure this is solved in the next release.

Thanks.

**Comment by jfederico** [comment]
Merged into v2.2-stable
