### ISSUE TITLE
'No session variable set' when viewing as non-admin

### ISSUE THREAD

**Issue by jacks0n** [blindsidenetworks/moodle-mod_bigbluebuttonbn#120]
When viewing a Big Blue Button page as a non-admin user (e.g. `/mod/bigbluebuttonbn/view.php?id=1`), the AJAX call to `/mod/bigbluebuttonbn/bbb_broker.php` returns `400 Bad Request. No session variable set`. However when viewing the same page as admin, the same AJAX call returns 200, and the 'Join' button renders and works correctly.

When viewing as admin, that AJAX call returns the following content:
```
YUI.Env.DataSource.callbacks.yui_3_17_2_1_1551309096286_27({"info":{"returncode":"FAILED","messageKey":"notFound","message":"We could not find a meeting with that meeting ID"},"running":false,"status":{"join_url":null,"join_button_text":"Join session","end_button_text":"End session","can_join":true,"message":"This conference room is ready. You can join the session now.","can_end":false}});
```

Clicking the 'Join' button as admin successfully joins the BBB room and seems to work fine, despite the "We could not find a meeting with that meeting ID" error. Any ideas what's causing this?

We're running mod_bigbluebuttonbn v2.2.10 (2017101018) and Moodle v3.6.2 (20190222).

**Comment by jfederico** [comment]
I have no problems joining a session with an student account using the same versions. It may be a configuration issue on your Room/Activity.

I would not discard a bug, but it is hard to tell if it is not reproducible. In such case we need more than the description to do that.

Is it happening with all the other users/roles or only students?
Are you seeing something else in the browser console?
Is the room set to wait for moderator to join?
Is the room set for using groups?
Is there any other restriction (any of the new ones) applied to that particular activity?
Did this happened since you upgraded or it is a fresh installation?
Is it only happening on 3.6?

As you can see, there are too many variables we would have to exhaust.

If this is a development/testing environment, it would help to narrow dawn if you try a previus version and tell us if you get it to work properly.

**Comment by jacks0n** [comment]
@jfederico it seems to be only happening with student roles, not admin. We're using Drupal SSO for some students, but that doesn't seem to effect it as it does not work with students who are authenticating via Moodle natively.

In the Chrome console I see this:
```
Unchecked runtime.lastError: The message port closed before a response was received.
yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:5828 warn: The moodle-core-notification parent module has been deprecated. Please use one of its subclasses instead.
yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:5126 GET https://rc.managementtree.com.au/learning/mod/bigbluebuttonbn/bbb_broker.php?action=meeting_info&id=f558a426823926447d3e47b9d01891cbb90b7267-8-2&bigbluebuttonbn=2&updatecache=false&callback=YUI.Env.DataSource.callbacks.yui_3_17_2_1_1558514235794_27 net::ERR_ABORTED 400 (Bad Request. No session variable set)
(anonymous) @ view.php?id=87:639
(anonymous) @ view.php?id=87:649
first.js:81444 Page is missing a drawer region
first.js:81447 Page is missing a drawer toggle link
```

In Firefox the console shows this:
```
moodle-core-event: Global event published: FORM_ERROR yui_combo.php:5828:31
moodle-core-event: Global event published: BLOCK_CONTENT_UPDATED yui_combo.php:5828:31
warn: The moodle-core-notification parent module has been deprecated. Please use one of its subclasses instead. yui_combo.php:5828:31
The script from “https://rc.managementtree.com.au/learning/mod/bigbluebuttonbn/bbb_broker.php?action=meeting_info&id=f558a426823926447d3e47b9d01891cbb90b7267-8-2&bigbluebuttonbn=2&updatecache=false&callback=YUI.Env.DataSource.callbacks.yui_3_17_2_1_1558514144914_27” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.[Learn More] view.php
Loading failed for the <script> with source “https://rc.managementtree.com.au/learning/mod/bigbluebuttonbn/bbb_broker.php?action=meeting_info&id=f558a426823926447d3e47b9d01891cbb90b7267-8-2&bigbluebuttonbn=2&updatecache=false&callback=YUI.Env.DataSource.callbacks.yui_3_17_2_1_1558514144914_27”. view.php:1:1
Page is missing a drawer region first.js:81444:13
Page is missing a drawer toggle link
```

- The room is not set to wait for a moderator to join.
- All users who are enrolled can view.
- Groups are not being used.
- There are no restrictions set.
- I've never been able to get it to work, it was based on an existing Moodle installation but fresh BBB install. I've tried several BBB mod versions.
- Currently Moodle 3.6.2 is installed, and BBB mod 2.3dev (2018040110).
- I've tried Flash and HTML5.

I'm not a Moodle developer but can debug PHP. Where is the session data set? Where would be a good place to start debugging this?

**Comment by jfederico** [comment]
We are on 2.3-beta1 (2019042001), I would start updating the version.

The SSO with drupal should not be an issue at all, as long as you are authenticated, you should be able to access the service. It may be an issue with te session in Moodle when the user is authenticated using an external source. But I am not sure.

**Comment by jacks0n** [comment]
@jfederico I tried upgrading to the latest version 2.3-beta1 but that didn't fix it unfortunately. I originally thought it might be the Drupal SSO, but the issue occurs with all students, regardless of the auth method. Does the `No session variable set` error get triggered when the admin user disables the 'Join' button usually, or is it a technical error that shouldn't generally happen? What would be the next steps to debug? Thanks.

**Comment by jfederico** [comment]
I stil have not been able to reproduce it. No idea what is in your deployment. For what I understand you have never used BBB in your Moodle Server 

>I've never been able to get it to work, it was based on an existing Moodle installation but fresh BBB install. I've tried several BBB mod versions.

You did not respond my question

Is it only happening on 3.6? Have you tried a different version of Moodle.

Also, if you install the previus version (2.2.12). Does that work for you?
