### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by dinism** [blindsidenetworks/moodle-mod_bigbluebuttonbn#130]
Once the RecordingsBN plugin has the warning: "This plugin has been phased out ..." i think it's good idea change the AMOS string modulename_help | bigbluebuttonbn:
"... To view later recordings, add a RecordingsBN resource to this course."
Thanks for the plugin. It's only a sugestion.
I'm a PT-PT translator.

**Comment by jfederico** [comment]
Good point, thanks!
