### ISSUE TITLE
Database error after Logout from BBB

### ISSUE THREAD

**Issue by harajukakei** [blindsidenetworks/moodle-mod_bigbluebuttonbn#150]
If i click logout from any webinar that created by this mod, i have this error :
`Debug info: SQLState: 42000<br>
Error Code: 102<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'LIMIT'.<br>

SELECT meta FROM mdl_bigbluebuttonbn_logs
WHERE userid = '2' AND log = 'Join'
ORDER BY ID DESC LIMIT 1
[array (
0 => '2',
)]
Error code: dmlreadexception
Stack trace:
line 486 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 324 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 431 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 896 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 972 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
line 1587 of \lib\dml\moodle_database.php: call to sqlsrv_native_moodle_database->get_records_sql()
line 1660 of \lib\dml\moodle_database.php: call to moodle_database->get_record_sql()
line 152 of \mod\bigbluebuttonbn\bbb_view.php: call to moodle_database->get_field_sql()`

using Moodle 3.7 with MS SQL 2017 backend. any solution ?

**Comment by jfederico** [comment]
See https://tracker.moodle.org/browse/CONTRIB-7894 PR#154
