### ISSUE TITLE
Invalid course module ID

### ISSUE THREAD

**Issue by pablorebollo** [blindsidenetworks/moodle-mod_bigbluebuttonbn#153]
The following error message is displayed when adding "Join open" or "Join closed".  The module has the CONTRIB-7874 and CONTRIB-7875 applied.

Invalid course module ID

Debug info: SELECT id,course FROM {course_modules} WHERE id IS NULL
[array (
)]
Error code: invalidcoursemodule

Stack trace:
line 1562 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1538 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 7115 of /lib/accesslib.php: call to moodle_database->get_record()
line 1592 of /lib/weblib.php: call to context_module::instance()
line 689 of /mod/bigbluebuttonbn/lib.php: call to format_module_intro()
line 646 of /mod/bigbluebuttonbn/lib.php: call to bigbluebuttonbn_process_post_save_event()
line 178 of /mod/bigbluebuttonbn/lib.php: call to bigbluebuttonbn_process_post_save()
line 575 of /course/modlib.php: call to bigbluebuttonbn_update_instance()
line 152 of /course/modedit.php: call to update_moduleinfo()

![Screen Shot 2019-11-05 at 9 14 35 AM](https://user-images.githubusercontent.com/28874398/68210824-be14c200-ffac-11e9-840c-07cc05b5a603.png)

![Screen Shot 2019-11-05 at 9 10 56 AM](https://user-images.githubusercontent.com/28874398/68210578-34fd8b00-ffac-11e9-87d8-3bf92cb45f50.png)

**Comment by jfederico** [comment]
Thanks for the report.
Was the problem there before applying the two patches?

**Comment by pablorebollo** [comment]
The problem happened after applying the patch and trying to set a "Join open" or "Join closed" date and time information.  A similar problem happened before applying the patch when selecting the option "Send notification".  The patch solve the error for "Send notification" but cause a new error for "Join open" or "Join closed" options.

All the tests were performed using a plain 3.7.2 (Build: 20190909) Moodle instance with BigBlueButtonBN 2.3 (2019042005) plugin.

**Comment by jfederico** [comment]
PR #156 merged

**Comment by pablorebollo** [comment]
The changes were applied to the test environment.  All the messages errors gone.  Many thanks for your support.
