### ISSUE TITLE
mod_bigbluebuttonbn\privacy\provider::get_contexts_for_userid

### ISSUE THREAD

**Issue by voztovoice** [blindsidenetworks/moodle-mod_bigbluebuttonbn#157]
Hello,
this happens from today:
#0 /home/voztovoice/public_html/campus/mod/bigbluebuttonbn/classes/privacy/provider.php(97): default_error_handler(4096, 'Argument 1 pass...', '/home/voztovoic...', 97, Array)
#1 /home/voztovoice/public_html/campus/privacy/classes/local/legacy_polyfill.php(76): mod_bigbluebuttonbn\privacy\provider::_get_contexts_for_userid('1390')
#2 [internal function]: mod_bigbluebuttonbn\privacy\provider::get_contexts_for_userid('1390')
#3 /home/voztovoice/public_html/campus/lib/moodlelib.php(7776): call_user_func_array('mod_bigbluebutt...', Array)
#4 /home/voztovoice/public_html/campus/privacy/classes/manager.php(495): component_class_callback('mod_bigbluebutt...', 'get_contexts_fo...', Array)
#5 /home/voztovoice/public_html/campus/privacy/classes/manager.php(528): core_privacy\manager::component_class_callback('mod_bigbluebutt...', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#6 /home/voztovoice/public_html/campus/privacy/classes/manager.php(237): core_privacy\manager->handled_component_class_callback('mod_bigbluebutt...', 'core_privacy\\lo...', 'get_contexts_fo...', Array)
#7 /home/voztovoice/public_html/campus/admin/tool/dataprivacy/classes/task/initiate_data_request_task.php(81): core_privacy\manager->get_contexts_for_userid('1390')
#8 /home/voztovoice/public_html/campus/lib/cronlib.php(156): tool_dataprivacy\task\initiate_data_request_task->execute()
#9 /home/voztovoice/public_html/campus/lib/cronlib.php(74): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\initiate_data_request_task))
#10 /home/voztovoice/public_html/campus/admin/cli/cron.php(61): cron_run()
#11 {main}

Moodle version: 3.7.3
BigBlueButton module version: 2.3.1

**Comment by jfederico** [comment]
Tra
