### ISSUE TITLE
Feature request: server configurable on module level

### ISSUE THREAD

**Issue by rschrenk** [blindsidenetworks/moodle-mod_bigbluebuttonbn#192]
Hello,

we are driving a multi-tenancy Moodle site with currently 400 schools. We intend to have a few thousand schools when we reached our maximum capacity. Most of them are economically independent from us and we can not afford providing BBB-servers for all of them.

Therefore I want to suggest a new feature.

Moodle-Admins could control by a capability, if users are able to specify an alternative BBB-Server when editing the course module itself. As alternative Managers (eg. on course category level) could specify a default server for all courses in their range.

Kind regards
Robert Schrenk

**Comment by cmersinli** [comment]
@rschrenk  i think you wanna this   https://www.linkedin.com/in/cmersinli/detail/recent-activity/

**Comment by rschrenk** [comment]
Hello,

I see the functionality on the screenshot, but not on our system. I upgraded on our development moodle to the latest version from moodle.org - nothing like that either.

We are using boost_campus-theme and I am logged in as admin.

Do you have any idea why I can't see such functionality?

Kind regards

**Comment by cmersinli** [comment]
@rschrenk no this is my bigbluebutton code. I edited official code.

**Comment by rschrenk** [comment]
Ok, so it would be nice if this was integrated into the officiel plugin code.

**Comment by jfederico** [comment]
This has been discussed before. It is not a feature we want to have in the plugin. We actually have had to remove that functionality from other integrations in the past.

What you really need is a load balancing solution for your BBB servers. The BBB URL and secret can be hiden from your tenant administrators by adding it to the config.php file.

In regards to the Load Balancing Solution, you may want to take a look at https://github.com/blindsidenetworks/scalelite

This is a project that we just open-sourced a few weeks ago, precisely for giving to the workd a way to tackle the high demand is now needed as a concecuence of the COVID-19 situation.

It is not multitenant, and it requires skills to set it up properly, but that is indeed the way to go.

Others have even build their own LB for that.

Now in terms of your moodle deployment, in my personal opinion and wihtout knowing much about your architecture, I would say that you want to reconsider the way you are deploying. In Moodle Cloud for instance, they have a container per tenant, so, they can have specific BBB credentials per customer. That is the way things should be.

Well, that is my 5 cents, I hope is of any help
