### ISSUE TITLE
Problems with UTF-8

### ISSUE THREAD

**Issue by bidikov** [blindsidenetworks/moodle-mod_bigbluebuttonbn#193]
Hi team,
Great plugin and we saw a issue connected to the usage of UTF-8 in sessions.

This function seams to be the problem:
function bigbluebuttonbn_html2text($html, $len = 0) {
    $text = strip_tags($html);
    $text = str_replace('&nbsp;', ' ', $text);
    $textlen = strlen($text);
    $text = substr($text, 0, $len);
    if ($textlen > $len) {
        $text .= '...';
    }
    return $text;
}

I suppose we need of mb_string versions of the php functions resolves the issue
And also setting of the UTF-8 for all mb operations with:
mb_internal_encoding("UTF-8");

The error log we locates the error:
F, [2020-03-19T11:31:55.937893] FATAL -- : [8102237c-ff68-4cd7-a6ff-7bdcdf394c19]
[8102237c-ff68-4cd7-a6ff-7bdcdf394c19] ActionController::BadRequest (Invalid query parameters: Invalid encoding for parameter: Телеконференциска соба за консулт�...):

I think this needs to be looked on the plugin level for all string operation since Moodle is already UTF-8 ready ...

Best regards,

**Comment by jfederico** [comment]
Thanks for the suggestion @bidikov , These are the king of error we don't catch working on English only.

A few other people have been dealing with the issue. The PR is actually here https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/pull/194 which was merged on master. I'll pull it to v2.3-stable today

If you can give it a try and confirm if that fixed the problem, that would be great.

**Comment by jfederico** [comment]
It is not nice when someone just shows up to report a bug or a problem but when you ask them to confirm the patch worked they just disapear.

**Comment by bidikov** [comment]
Hi, sorry for the late response... but beeing busy with the faculty jobs i forgot to report the situation...
First, the PR seems to work... of course being techical we decided that it's best that we standardise our eforts so we transliterate the name of the rooms before we send them to moodle so the issue becomes wery rare...

We will be going over mod_bigbluebutton after our exams end (around 20.7.2020) and we like to fix some loose ends and upgrade to moodle 3.9 so that will be a interesring ride going 3.7->3,8->3.9 for several systems...

I will try to be more responsive... if time allows since after 10.03.2020 and Covid19 i seem to work 16+ hours per day :)
