### ISSUE TITLE
Totara unit tests fail

### ISSUE THREAD

**Issue by ledship** [blindsidenetworks/moodle-mod_bigbluebuttonbn#198]
3 unit tests fail on Totara.
The first two are rather simple and the changes shouldn't cause any problems.

One is incorrectly bitmasked files, I have submitted pull request #195 to fix.
`vendor/bin/phpunit --colors totara_core_totara_testcase totara/core/tests/totara_test.php`

Second is the install.xml was different to a generated version, saving that through the XMLDB editor fixes that and that is in pull request #196 
 `vendor/bin/phpunit --colors tool_xmldb_instal_xml_testcase admin/tool/xmldb/tests/install_xml_test.php`

Third is CAP_PREVENT being set on archetypes in the access file. 
According to Totara this does nothing, though perhaps there is some funky permission stuff happening in this plugin?
I submitted pull request #197 to fix this.
`vendor/bin/phpunit --colors totara_core_access_testcase totara/core/tests/access_test.php`

Please let me know if you have any questions.

**Comment by danmarsden** [comment]
Thanks Alex - @jfederico - let us know if you have any questions around this.
Totara runs a bunch of extra unit tests on top of the Moodle ones that check 3rd party plugins for compliance with various standards - as we run Continous integration processes, these issues block your plugin being deployed to Totara production sites so it would be good if you could merge Alex's pull requests at some point (although I'm sure you're all crazy busy atm!) - thanks!

**Comment by jfederico** [comment]
Hi @danmarsden, thanks for all this work. I wouldnot be able to do it myself!

Yes, we are crazy busy, but there are priorities, that is for sure ;)

I'll be working on the merges during the day tomorrow. I just triggered one a few minutes ago, but we are on Travis, and it will take some time.

Thanks again

**Comment by jfederico** [comment]
Done!
