### ISSUE TITLE
Feature request: notification should contain link to BBB

### ISSUE THREAD

**Issue by Richardvi** [blindsidenetworks/moodle-mod_bigbluebuttonbn#200]
When you set up a BBB activity in Moodle, you have the option to select 'send notification'.

The notification however doesn't contain a link to the BBB activity or a link to the Moodle course.

**Comment by jfederico** [comment]
The actual place for feature request is JIRA, I created an issue already https://tracker.moodle.org/browse/CONTRIB-7645

Thanks for the suggestion.

**Comment by Richardvi** [comment]
But that seems to be a completely different issue. Do you want me to make a new issue or dis you post the wrong link accidentally?

**Comment by Richardvi** [comment]
Found it: https://tracker.moodle.org/browse/CONTRIB-8029

THanks!
