### ISSUE TITLE
Is this still a thing? SSL on recording thumbnails

### ISSUE THREAD

**Issue by paul1278** [blindsidenetworks/moodle-mod_bigbluebuttonbn#201]
Can we enable https on the URLs to the recording-thumbnails?
Because with http Chrome etc. always mark the page as `Not secure`

**Comment by davidpesce** [comment]
This is an issue with scalelite and was resolved here: https://github.com/blindsidenetworks/scalelite/pull/139

You can update your scalelite to version 1.0.2 to resolve this issue. No update to the Moodle plugin is required.

**Comment by paul1278** [comment]
Thank you for that answer! Already updated, but kind of forgot about this issue
