### ISSUE TITLE
When a session recording is being transcoded, clearly show this is happening in moodle

### ISSUE THREAD

**Issue by brendanheywood** [blindsidenetworks/moodle-mod_bigbluebuttonbn#219]
So people don't freak out and think their recording is lost. In an ideal world would have an eta / estimate, but just a place holder would be a good start

**Comment by jfederico** [comment]
The thing is that the time for processing is variable, and depends enterely on the server processing the recordings.

I agree, it would be nice to have such a feature, but until BBB implements something for that, there is nothing we can do within the plugin.

**Comment by brendanheywood** [comment]
All we need to know if whether there is an expectation that a recording should arrive later, and then just show a message. If 'recording_default' is on this should definitely show a message.

**Comment by jfederico** [comment]
Yeah, thanks for the reminder @brendanheywood . I understand the feature request. This is why I tagged it. You can say that it officially made it to the road map :) (https://tracker.moodle.org/browse/CONTRIB-8159)

But what I am saying is that we must have the status gathered from BBB. That is the best and less invasive way but requires changes to the scripts for processing recordings on BBB. There is another possibility, but requires more logic in the plugin, so I would rather not go that way.

The thing is that I am not trying to solve the problem for Moodle only. I am looking for a solution for every other integration we have, you know what I mean?

Either way this won't be part of the first 2.4 release, but likely the next one. Not sure if as a patch or as part of the next minor (2.5), it depends of the approach we decide.

**Comment by jfederico** [comment]
The development of this feature will be tracked on JIRA https://tracker.moodle.org/browse/CONTRIB-8159

**Comment by brendanheywood** [comment]
thanks @jfederico - would you prefer we log things here or in the tracker?
