### ISSUE TITLE
LOADBALANCER_SECRET giving error "You did not pass the checksum security check" in Moodle

### ISSUE THREAD

**Issue by HossamAhmedHamdi** [blindsidenetworks/moodle-mod_bigbluebuttonbn#223]
Steps I made:
1- Installed Scalelite, Redis, Docker and BBB on a server named "BBBM" for example.
2- Installed BBB on 3 other servers "BBB1, BBB2 and BBB3" for example.
3- Added the 3 servers to the pool and checked them they are all enabled and online.
4- I logged to Moodle and went to BBB plugin and added the link to the main server bbbm.example.com/bigbluebutton and the load balancer secret in "Shared Secret" field.
5- When I try to open any classroom or create I get this error "bigbluebuttonbn/You did not pass the checksum security check".

What I Checked:
1- BBB is working on main server.
2- Checked Scalelite, Docker and Redis ,,etc.
3- Tested connection with the BBB secret on the main server it's working.

Any help?

**Comment by jfederico** [comment]
Your question has nothing to do with the plugin. You should bring this type of questions to the corresponding channel. the bigbluebutton goole groups are the first place to go.
