### ISSUE TITLE
Scalelite "bigbluebuttonbn/unreachable" error

### ISSUE THREAD

**Issue by gethanos** [blindsidenetworks/moodle-mod_bigbluebuttonbn#228]
Hi,
I have 3 BBB Servers and a moodle Instance with many courses and groups for students. I have also setup a dedicated VM with scalelite.
It seems that randomly, but very often i get "bigbluebuttonbn/unreachable" page on moodle and on the API (Scalelite) i get logs like:
[d221244f-590f-4d10-be53-f12c4980e944] The requested meeting 2260ee07763ee8f8a0bd8ef0057b52215332b694-184-287[719] does not exist

if someone else joins on another class a server and I jump to another server (i think that's when it happens), I manage to enter the bbb room. Any ideas?

Bests

**Comment by gethanos** [comment]
I tried to clean up the moodle database from meeting IDs, also i tried to join from courses without groups, and also with older version of the Moodle Plugin. Also different Moodle instance. Same behavior, I also installed a fresh scalelite server to test. 

Anything left to test?
Bests

**Comment by gethanos** [comment]
Just an update:
After a lot of tests, it seems that after i renamed a students group in order not to have any Greek characters, but only latin, the specific Room have work! Is there something wrong with encoding that might causing issues like those?
There are some rooms that will work after you "hit" one, two times the Join the Meeting, but for some, it;s just impossible to join. This Room that i am talking about was one of them.

**Comment by gethanos** [comment]
I managed to make it work by recreating every bigbluebuttonbn activity in the courses. few times i had to do it twice or even more. Most Courses now work, but randomly especially in courses with group names that contain Greek & Special characters (like"-") and numbers are getting rejected again with "bigbluebuttonbn/unreachable" error.

Bests!

**Comment by Francisco-veka** [comment]
Estimado gethanos soy algo nuevo en BBB y me interezo mucho la solucion para el balanceo de BBB estoy un poco trabado para poder instalar SCALELITE, me podrias mandar alguna guia de como instalar SCALELITE , DE ANTE MANO TE AGRADEZCO TU TIEMPO.

**Comment by jfederico** [comment]
Guys, I am going to close this issue because it has noting to do with the plugin. YOu may be of better luck if you post your questions to the bigbluebuttonbn google groups
