### ISSUE TITLE
Welcome message in Turkish is wrong

### ISSUE THREAD

**Issue by dseral** [blindsidenetworks/moodle-mod_bigbluebuttonbn#229]
Hello,
I was faced some issue that if welcome message is not set in this case default welcome message (Turkish)  which appear in BBB server being wrong..  How can I fix this message?
Thanks
Devrim

**Comment by jfederico** [comment]
When you download the language package, bigbluebuttonbn is inclueded. So, you can edit your local file or make your changes on AMOS https://lang.moodle.org/

Also, this is not an space for user support, it is used more for development. You may be of better luck if you post these kind of questions in the Moodle forums.
