### ISSUE TITLE
CONTRIB-8044: Core tests are failing with "unexpected new CFG->bigbluebuttonbn value" error

### ISSUE THREAD

**Issue by golenkovm** [blindsidenetworks/moodle-mod_bigbluebuttonbn#230]
Full error:

```
Time: 4.69 seconds, Memory: 206.00 MB

There was 1 error:

1) core_test_generator_testcase::test_get_plugin_generator_good_case
Warning: unexpected new $CFG->bigbluebuttonbn value

/var/www/site/lib/phpunit/classes/util.php:296
/var/www/site/lib/phpunit/classes/advanced_testcase.php:503
/var/www/site/lib/phpunit/classes/advanced_testcase.php:132

To re-run:
 vendor/bin/phpunit "core_test_generator_testcase" lib/testing/tests/generator_test.php

ERRORS!
Tests: 1, Assertions: 1, Errors: 1.
```

**Comment by davidpesce** [comment]
@golenkovm - Thanks for reporting this and adding a PR. Is this only with a specific version of Moodle? I'm running the tests on v3.8.3+ and not seeing an error.

**Comment by dmitriim** [comment]
@golenkovm  I'm wandering if this is because of the order of the  test or because of the version of moodle?

**Comment by davidpesce** [comment]
@dmitriim - I don't think it's the order of the tests, because it's only running a single test.

**Comment by ledship** [comment]
@davidpesce I have found that this happens all the time on Totara 9 and 10's which run Moodle 3.0 and 3.2. You might also have to run the full test suite, I can't replicate it locally when running a single test but in our CI it fails when running all the tests.
