### ISSUE TITLE
bigbluebuttonbn/You have exceeded the max number of concurrent meetings.

### ISSUE THREAD

**Issue by AimvenDragtow** [blindsidenetworks/moodle-mod_bigbluebuttonbn#233]
Hi,
I can't open bbb session anymore because of this error and didn't find any doc about this error message, very random.
I want to know what this error means while i have no opened sessions and meetings on moodle.
![image](https://user-images.githubusercontent.com/40371962/79465405-33bc9980-7ff3-11ea-9a7c-ad57162e1d88.png)
thanks for helping

**Comment by jfederico** [comment]
There are a few possibilities. One is that you are using a free server provided by someone who limited the number of sessions though configuration.

Either way, unless is a bug and you present the steps for reproducing it, you should look for help in the bigbluebutton google goups.
