### ISSUE TITLE
Configuration settings for Participant configuration

### ISSUE THREAD

**Issue by callumlew** [blindsidenetworks/moodle-mod_bigbluebuttonbn#236]
If you select custom Moodle roles within the plugin settings to have Moderator by default these are not reflected at the activity level automatically.  However, you can manually add these at the activity level.

Thanks

**Comment by jfederico** [comment]
That is the expected behaviour. The default settings only affect newly created activities. YOu can see it as a template used on crreation.

If you change the parameters you would have to manually change every instance in order to see those changes reflected.
