### ISSUE TITLE
Configure meeting room from the plugin

### ISSUE THREAD

**Issue by ppv1979** [blindsidenetworks/moodle-mod_bigbluebuttonbn#237]
Starting from version 2.2 the API of BigBlueButton allows to set the following parameters when you creating a meeting room with create() function:
lockSettingsDisableCam
lockSettingsDisableMic
lockSettingsDisablePrivateChat
lockSettingsDisablePublicChat
lockSettingsDisableNote
lockSettingsHideUserList
lockSettingsLockedLayout
lockSettingsLockOnJoin
lockSettingsLockOnJoinConfigurable

Can we let our teachers to configure some of them from the plugin's settings?

**Comment by brendanheywood** [comment]
+1

**Comment by brendanheywood** [comment]
We will be working on a pull request for this shortly

**Comment by ppv1979** [comment]
@brendanheywood, that's great!

**Comment by jfederico** [comment]
Thanks @brendanheywood and @Peterburnett  yeah, the PR is already open. I just tagged it for review
