### ISSUE TITLE
Feature Request: Add default presentation pdf to the activity config

### ISSUE THREAD

**Issue by IJOL** [blindsidenetworks/moodle-mod_bigbluebuttonbn#238]
Hola a todos:

So the meeting room will be initiated with a presentation configured in the usual way in moodle ( like when adding an image to course config or alike ).

Thanks in advance and keep on the good work, maybe with some guidance I could start to scratch my itch, but better try to gather some input from the community before trying to tweak things my way. any help will be very appreciated.

Saludos,
IJOL

**Comment by jfederico** [comment]
That feature is already implemented. Although it comes disabled by default

![image](https://user-images.githubusercontent.com/578359/87201614-f5bad300-c2cc-11ea-8624-58b60a74035e.png)

![image](https://user-images.githubusercontent.com/578359/87201652-053a1c00-c2cd-11ea-9a81-4fef6192bbda.png)

**Comment by IJOL** [comment]
From which version is that implemented? mine doesnt have it already...


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by IJOL** [comment]
Ok Ok did my homework, overlooked that option in the general activity
config, sorry for the noise..


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega
