### ISSUE TITLE
Support BBB meeting participants who don't have a Moodle account

### ISSUE THREAD

**Issue by abias** [blindsidenetworks/moodle-mod_bigbluebuttonbn#243]
I would like to propose to support BBB meeting participants who don't have a Moodle account.

This is useful for scenarios when BBB meetings have to be initiated through Moodle and which can't be moved to Greenlight for organizational reasons.

User story:
As a teacher, I have a weekly BBB meeting with my class within my Moodle course.
To the next meeting, I want to invite an external speaker as a one-time special session.
This external speaker does not have a Moodle account and it would be a large organizational overhead to create a Moodle account for him just to let him log into Moodle just once. Additionally, this external speaker should not have access to all the other materials in the Moodle course and Moodle system, so it would be another organizational overhead to create a Moodle role to forbid external speakers everything normal students are allowed to do in Moodle.

To support BBB meeting participants who don't have a Moodle account, at least the following things would have to be implemented:
* Implement an admin Setting which will work as a kill switch for this feature. Default will be no.
* Implement two capabililities:
** On capability to "Allow external participants" 
** Another capability to "Allow external moderators"
* Implement two activity instance settings for the BBB activity:
** On setting will enable "Allow external participants" per activity instance
** The other setting will enable "Allow external moderators" per activity instance
* Implement two more another activity instance settings "Restrict external access to scheduled meeting time" for the BBB activity
** The first setting will, if enabled, restrict the external access to within the scheduled meeting time of the BBB meeting
** The second setting will allow the teacher to add an optional lead time when the external access will be allowed _before_ the scheduled meeting time.
* Implement library functions to generate the external access assets
** We will need a meeting ID and a password wich can be used to access the meeting from outside of Moodle. This is similar to the meeting ID and passwords which can be generated for commercial VC systems like Zoom.
** We will need a combined external access URL which contains the meeting ID and the password and which will serve as one-click access to the meeting.
** These assets will have to be generated for external participants and external moderators separately
* Implement an information page for teachers
** This page will show the generated Meeting ID and the password 
** This page will show the external access URL where the meeting ID and the password can be entered
** This page will show the combined external access URL (including meeting ID and password)
** This page will show an email body text snipped for copying and pasting into emails to the external participants.
* Implement a page available on the external access URL
** This page must be accessible for non-logged-in users, even on installations with $CFG->forcelogin = true.
** This page will look similar to /mod/bigbluebuttonbn/view.php
** This page will accept meeting ID and password as URL parameters
** Alternatively, if meeting ID and password are not submitted within the URL, this page will show a form to submit this data
** As soon as the access with the given meeting ID and password is verified, the page will show the meeting title and the meeting access level (participant or moderator)
** The page will also show a form to allow the external user to set his name for the meeting (similar to how this is done in Greenlight)
** The page will check if the meeting is already accessible based on the setting for the scheduled access
** The page will respect the activity instance setting for "Wait for moderators" as well
** If all access constraints are confirmed, the page will show the "Enter meeting" or "Start meeting" buttons to the external user

**Comment by ppv1979** [comment]
+1, it would be great to have this opportunity!

**Comment by moodlebeuth** [comment]
+1, here are my five cents. ;-)

**Comment by christianwolters** [comment]
Hi @abias,

thank you for this proposal and good looking specification.
We have benn using mod_bbbbn for some weeks now,
and your idea matches some our support requests.

So how do we get this done?
Are you or anyone else plan to work on this (@jfederico, @ffdixon)

Cheers
Christian

**Comment by univietw** [comment]
@abias This is by far the most requested feature from our users at Uni Wien. We will program the feature exactly as you proposed starting today. Lets see if it is gonna be accepted.

**Comment by christianwolters** [comment]
@univietw thank you for picking this up!

If you are open to more help, I'd like to contribute, but I'm currently not able to take the lead on this.

You could start a github-project in your fork, where we organize corresponding issues according to the features outlined by @abias?

Cheers
Christian

**Comment by moodlebeuth** [comment]
Ok, if you need someone for testing purpose, please tell me! ;-)

Greetings,
Michael

**Comment by jfederico** [comment]
Hi guys,

Thanks for the suggestion. But just to be clear. The fact that we are open to requests and suggestions doesn't mean that we jump into the code as soon as we get them.

Especially because this is a problem that can be solved right now in other ways. Actually, as you know Greenlight would be the way to go. LTI links is another option. I understand the constrain of not being able to install Greenlight in your institutions, but still that is the natural way to solve the problem.

Now, the solution proposed adds a lot of complexity, and you know that just the settings as they are right now, are complex enough already.

Perhaps a workaround for the moment would be simply allow guests and enable the setting for "Allow participants to join the session" (something that was added to the BBB API in the last version, and just a few apps like Greenlight are making use of it)

We will be looking into this for sure, but right now there are more pressing things to be done, like releasing BigBlueButtonBN 2.4 before the fall term. It likely will go until the next release.

Now, if you want to contribute with code, lets try this. Let's move this conversation to Moodle Tracking system. We can use the issue that @univietw  already opened https://tracker.moodle.org/browse/CONTRIB-8152 or we can create a new one as this the simpler solution I was talking about.

I also forked the repo here with its own branch, so PRs can be open against that repo/branch and we keep travis busy only with that repo.

https://github.com/blindsidedev/moodle-mod_bigbluebuttonbn/tree/CONTRIB-8152

**Comment by partecipazionelab** [comment]
Dear @jfederico ,

what do you mean by "Greenlight is the way to go"? Is there a way to integrate greenlight into moodle creating an activity in moodle that generates a greenlight link?

What I have understood is that both GL and Moodle acts as frontend to BBB and those can coexist but can't talk to each other.

Thanks
Davide

**Comment by partecipazionelab** [comment]
Actually another valid approach is to open the bbb activity to guests. The only missing part is for the guest to choose an username before joining. This topic has been referred here: #257

**Comment by jfederico** [comment]
The development of this feature will be tracked on JIRA https://tracker.moodle.org/browse/CONTRIB-8152

**Comment by jfederico** [comment]
> Actually another valid approach is to open the bbb activity to guests. The only missing part is for the guest to choose an username before joining. This topic has been referred here: #257

Which I just said in my post :)

> Perhaps a workaround for the moment would be simply allow guests and enable the setting for "Allow participants to join the session" (something that was added to the BBB API in the last version, and just a few apps like Greenlight are making use of it)
