### ISSUE TITLE
new unit test failure in 3.9 and higher

### ISSUE THREAD

**Issue by danmarsden** [blindsidenetworks/moodle-mod_bigbluebuttonbn#255]
https://tracker.moodle.org/browse/MDL-68645 Implemented a new check which triggers unit test failures in BBB code:

1) mod_bigbluebuttonbn_lib_testcase::test_bigbluebuttonbn_reset_events
coding_exception: Coding error detected, it must be fixed by a programmer: Creating a mod_bigbluebuttonbn activity initialised the theme and output! (This should not happen. Creating an activity should be a pure back-end operation. Unnecessarily initialising the output mechanism at the wrong time can cause subtle bugs and is a significant performance hit. There is likely a call to an output function that caused it:

* line 687 of /lib/pagelib.php: call to moodle_page->initialise_theme_and_output()

2) mod_bigbluebuttonbn_lib_testcase::test_bigbluebuttonbn_print_overview
coding_exception: Coding error detected, it must be fixed by a programmer: Creating a mod_bigbluebuttonbn activity initialised the theme and output! (This should not happen. Creating an activity should be a pure back-end operation. Unnecessarily initialising the output mechanism at the wrong time can cause subtle bugs and is a significant performance hit. There is likely a call to an output function that caused it:

* line 687 of /lib/pagelib.php: call to moodle_page->initialise_theme_and_output()

**Comment by jfederico** [comment]
Hi @danmarsden 

Yeah, I did not know the why, but we noticed that the tests were broken anlong with other scripts run by travis.

This give us a good starting point. Although for the moment I had to disable the test :S. The show must continue I am afraid.

Thanks again,
