### ISSUE TITLE
Problem with approve joining a meeting 

### ISSUE THREAD

**Issue by MichaelSauerHTWdS** [blindsidenetworks/moodle-mod_bigbluebuttonbn#262]
We could used before BBB Version 2.2.15 a function to approve viewers by moderators in order to allow join the meeting. That doesn't work now (in Greenlight the function is still there).

It seems to us that the guest state isn't set and all moodle course members get the right to join the meeting without permission of a moderator.

Is that a wished feature? Could we get the old feature back. It's very annoying that someone could share a meeting without permission.

**Comment by steffen-moser** [comment]
Maybe it has been fixed in 2.2.16, see https://github.com/bigbluebutton/bigbluebutton/releases or here: https://github.com/bigbluebutton/bigbluebutton/pull/9687

**Comment by Atandil** [comment]
You ca fix it by small change in greenlight 
in
app/controllers/concerns/bbb_server.rb
add in line 57
    join_opts[:guest] = true if options[:require_moderator_approval] && !options[:user_is_moderator]

**Comment by MichaelSauerHTWdS** [comment]
> Maybe it has been fixed in 2.2.16, see https://github.com/bigbluebutton/bigbluebutton/releases or here: [bigbluebutton/bigbluebutton#9687](https://github.com/bigbluebutton/bigbluebutton/pull/9687)

Thanks a lot, that solved the problem for us!

**Comment by MichaelSauerHTWdS** [comment]
> You ca fix it by small change in greenlight
> in
> app/controllers/concerns/bbb_server.rb
> add in line 57
> join_opts[:guest] = true if options[:require_moderator_approval] && !options[:user_is_moderator]

Thank you for the suggestion, but we have no green light problem. I told that just in order to explain the behaviour
