### ISSUE TITLE
Sort the participants list

### ISSUE THREAD

**Issue by ffdixon** [blindsidenetworks/moodle-mod_bigbluebuttonbn#263]
Currently, the drop-down for Participants is not sorted

![image](https://user-images.githubusercontent.com/290351/84065779-e6c1c780-a992-11ea-98df-735b7dd45936.png)

To make it easier for teachers to pick out a user from the list, sort the users in the drop-down list.

**Comment by jfederico** [comment]
It is sorted by ID, there is PR open for that

**Comment by jfederico** [comment]
https://tracker.moodle.org/browse/CONTRIB-8113
