### ISSUE TITLE
The recording button is visible when rooms are set to 'Room/Activity Only'

### ISSUE THREAD

**Issue by Peterburnett** [blindsidenetworks/moodle-mod_bigbluebuttonbn#265]
This can create a bad UX when a user thinks they can record the session for later use, however the recording is not accessible. There should be a toggle to automatically hide the recording button in the room if the type is set to 'Room/Activity only'

**Comment by jfederico** [comment]
The development is tracked on [Moodle Tracker](https://tracker.moodle.org/browse/CONTRIB-8174)
