### ISSUE TITLE
Moodle 3.9 unable to create new element bbb in course

### ISSUE THREAD

**Issue by kallibr44** [blindsidenetworks/moodle-mod_bigbluebuttonbn#268]
installed Moodle 3.9 with PHP 7.3. I made all configs correct (tried with manual php request on bigblubutton api), but when i am creating new block in course, i'm getting next error: _**Error code: general_error_unable_connect**_. Traceback:
No response on wrap_simplexml_load_file
line 533 of /mod/bigbluebuttonbn/locallib.php: call to debugging()
line 507 of /mod/bigbluebuttonbn/locallib.php: call to bigbluebuttonbn_wrap_xml_load_file()
line 48 of /mod/bigbluebuttonbn/mod_form.php: call to bigbluebuttonbn_get_server_version()
line 214 of /lib/formslib.php: call to mod_bigbluebuttonbn_mod_form->definition()
line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
line 141 of /course/modedit.php: call to moodleform_mod->__construct()

I made some debug points in library and found what response from GET request came correct 
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>
, but finally response is just 1, and because of it, **_bigbluebuttonbn_get_server_version()_** (locallib.php line 505) function returning null. BUT calling this function manually instead of internal lib call, i'm getting correct answer (2.0). Please, can you fix that?

**Comment by kallibr44** [comment]
i'm sorry for the future about my english quality :)

**Comment by jfederico** [comment]
It seems that the response from the BBB server is incorrect. We have to change the way that is validated, but for the moment it is all we got.

I would try usinng the predfined test-install bbb server in the exact way that is shown next to the textbox in the admin settings. If that works, I would go to check your URL and/or BBB server

**Comment by kallibr44** [comment]
it doesn't working with bbb test-server too (tried raw curl request and got correct answer, but plugin giving 1 response)

**Comment by kallibr44** [comment]
In 2.3.4 this bug was gone! Thanks for update.
