### ISSUE TITLE
Multiple plugin instances in Moodle to integration different BBB clusters

### ISSUE THREAD

**Issue by schmidt-uni-leipzig** [blindsidenetworks/moodle-mod_bigbluebuttonbn#282]
In our case, it might be useful to integrate different BBB cluster into moodle. The different BBB cluster differ in fundamental configurations. To make it clear: we do not want to integrate single BBB nodes into Moodle but completely different BBB clusters.

At the moment, it seams, that it is not possible to integegrate multipe BBB clustes with different secrets each into Moodle.

Would it be possible to install the plugin twice and name the plugin instance differently? This way, we could use the plugin A in course A and plugin B (that points to a completly dfferent BBB cluster) in course B.

in total: How can we support and connect different BBB cluster in one Moodle instance?

Thank you for your reply.

**Comment by jfederico** [comment]
Deja vu. I have the feeling that I responded this already. I just don't remember where.

Anyways. Is not possible in the way you describe. The plugin can only handle one BBB server. What others have done, for SaaS deployments is one Moodle site per customer, therefore, each moodle site holds their own BBB server (with customized settings).

No, you can not install the plugin twice whithout making too many changes to the code. It is basically renaming the plugin, nbut the name is referenced everywhere.

If that is not an option, the next is to have a loadbalancer (such as scalelite) in front of the cluster of BBB servers. Moodle (the plugin) will see it as one, but the users will be sent indeed to different servers in the cluster.

Now, if what you need is customized bbb servers per customer/user, you are now talking about a multitenant solution. Which is what commercial vendors offer as a SaaS solution.

**Comment by aminvakil** [comment]
I could make it working with some tweaks, wanted to share it here:
Notes:
You should use Debian-based `rename`, it doesn't work on CentOS. (If your moodle is on CentOS just execute these commands on a Debian, compress it and then copy it to your Centos).
Download the plugin from moodle website (https://moodle.org/plugins/mod_bigbluebuttonbn) and copy it to `mod` directory on moodle webroot.

**YOU SHOULD NOT COPY THE EXACT SAME COMMANDS!!! CHANGE IT ACCORDING TO YOUR NEEDS OR SOMETHING BAD WILL HAPPEN!!!**

```
cp mod_bigbluebuttonbn_moodle39_2019042009.zip /var/www/html/mod
cd /var/www/html/mod
unzip mod_bigbluebuttonbn_moodle39_2019042009.zip
mv bigbluebuttonbn/ bigbluebutton2bn
unzip mod_bigbluebuttonbn_moodle39_2019042009.zip
mv bigbluebuttonbn/ bigbluebutton3bn
unzip mod_bigbluebuttonbn_moodle39_2019042009.zip
mv bigbluebuttonbn/ bigbluebutton4bn
cd bigbluebutton2bn/
find . -type f -exec sed -i "s/bigbluebutton/bigbluebutton2/g" {} \;
cd ../bigbluebutton3bn/
find . -type f -exec sed -i "s/bigbluebutton/bigbluebutton3/g" {} \;
cd ../bigbluebutton4bn/
find . -type f -exec sed -i "s/bigbluebutton/bigbluebutton4/g" {} \;
cd ../
cd bigbluebutton2bn/
find . -type f -exec sed -i "s/BIGBLUEBUTTON/BIGBLUEBUTTON2/g" {} \;
cd ../bigbluebutton3bn/
find . -type f -exec sed -i "s/BIGBLUEBUTTON/BIGBLUEBUTTON3/g" {} \;
cd ../bigbluebutton4bn/
find . -type f -exec sed -i "s/BIGBLUEBUTTON/BIGBLUEBUTTON4/g" {} \;
cd ../bigbluebutton2bn/
find . -type f -exec sed -i "s/BigBlueButton/BigBlueButton2/g" {} \;
cd ../bigbluebutton3bn/
find . -type f -exec sed -i "s/BigBlueButton/BigBlueButton3/g" {} \;
cd ../bigbluebutton4bn/
find . -type f -exec sed -i "s/BigBlueButton/BigBlueButton4/g" {} \;
cd ../bigbluebutton2bn/
find . -execdir rename 's/bigbluebutton/bigbluebutton2/' '{}' \+
cd ../bigbluebutton3bn/
find . -execdir rename 's/bigbluebutton/bigbluebutton3/' '{}' \+
cd ../bigbluebutton4bn/
find . -execdir rename 's/bigbluebutton/bigbluebutton4/' '{}' \+
```

**Comment by gpallaris** [comment]
> find . -execdir rename 's/bigbluebutton/bigbluebutton2/' '{}' \+
> cd ../bigbluebutton3bn/

Thanks for sharing.

I go through the steps. I also upload the clone plugin. Everything seems to be installed successfully 
I edit and save BBB1 Server/Setting then BBB2 Server/Settings successfully BUT when i want to add an activity using 2nd BBB, the module is always the 1st BBB.

Is it normal during the
cd ../bigbluebutton2bn/
find . -execdir rename 's/bigbluebutton/bigbluebutton2/' '{}' \+

to Get Perl notice/warning like :
perl: warning: Setting locale failed.

thanks in advance
G

**Comment by aminvakil** [comment]
I have tested this on debian 10 buster `rename`, and I didn't get through the differences between different `rename` versions on different distributions, it may be because of that.

**Comment by gpallaris** [comment]
> I have tested this on debian 10 buster `rename`, and I didn't get through the differences between different `rename` versions on different distributions, it may be because of that.

Thanks for replying back Aminvakil. I will try it on Debian 10 then. 

In the meantime I would’ve grateful if you can attach a renamed/duplicate version to test it on my Moodle installation.

best
g

**Comment by aminvakil** [comment]
> In the meantime I would’ve grateful if you can attach a renamed/duplicate version to test it on my Moodle installation.

Sure.
There are 6 instances of bigbluebutton moodle plugin here and they're working fine for me, but use them at your own risk.

[big.tar.gz](https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/files/7696527/big.tar.gz)

**Comment by gpallaris** [comment]
> > In the meantime I would’ve grateful if you can attach a renamed/duplicate version to test it on my Moodle installation.
> 
> Sure. There are 6 instances of bigbluebutton moodle plugin here and they're working fine for me, but use them at your own risk.
> 
> [big.tar.gz](https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/files/7696527/big.tar.gz)

Thank you aminvakil ! It works fine in Latest versions of Moodle.  
I couldn't make it work on version 3.8 even though it can be installed.
