### ISSUE TITLE
Plugin display name

### ISSUE THREAD

**Issue by amohideen** [blindsidenetworks/moodle-mod_bigbluebuttonbn#287]
Is it possible to set the name of the plugin to be different or a custom name in moodle's activities list? 
for an example display "BigBlueButtonBN" as "Live Class"?

**Comment by jfederico** [comment]
You can change the language file locally in the plugin or override your labguage package. in the end is just a tag

https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/blob/master/lang/en/bigbluebuttonbn.php#L44

**Comment by amohideen** [comment]
Thanks, I'll check it out.

**Comment by amohideen** [comment]
I changed the code to:
//$string['modulename'] = 'BigBlueButtonBN';
$string['modulename'] = 'LiveSession';

and restarted the apache (in case)
still did not work for me, it is still displaying "BigBlueButtonBN" in the activity list (pics attached). 
I will appreciate any more help on this, please. 
![image](https://user-images.githubusercontent.com/16897993/92336384-e15e4100-f097-11ea-8054-e46ecb30d5a7.png)
