### ISSUE TITLE
Question: Can the Moodle administrator list all the recordings made using BBB ?

### ISSUE THREAD

**Issue by parreitu** [blindsidenetworks/moodle-mod_bigbluebuttonbn#304]
In Greenlight the administrator has access to all the recordings made accessing BBB trough Greenlight. 

Using Moodle, a teacher has access to the recordings made through each BBB activity, but the Moodle administrator has not a way to list all the recordings made using BBB

Is there any way to solve it ?

In order to control the size of the recordings, we would like to know if there are very old recordings, for example recordings of finished courses, and to know which is the activity that each recording belong to.

Thanks

**Comment by jfederico** [comment]
No, there is no way right ow to do that from Moodle. You could fetch the recordings using the API if you are the BBB administrator and know the secret, but it is all XML. Not very friendly to users.

For that you can use https://mconf.github.io/api-mate/
