### ISSUE TITLE
list recording from deleted bigbluebuttonbn activity

### ISSUE THREAD

**Issue by mojtaba82** [blindsidenetworks/moodle-mod_bigbluebuttonbn#307]
I accidently remove a bigbluebuttonbn activity and I add another bigbluebuttonbn activity.
How can I list previous bigbluebuttonbn recordings to this new bigbluebuttonbn activity?
I had all data such as meetingid from previous bigbluebuttonbn activity.
Please help me.

**Comment by mojtaba82** [comment]
I have backup of previous database and access to it. I cant restore all database. Please help me to access records.
Records is not deleted from bbb server.

**Comment by jfederico** [comment]
You can not restore the activity (easily). But you can import the recording from a deleted activity. You won't have access to manage the actual recording, but you can still access it, even change the name and description to the link that is generated on import.

Using the plugin settings enable the options **Import recordings enabled** and **Import recordings from deleted activities enabled**, go to the new activity and click **Import recording**, from the drop-down select the same course and the recording should be shown. click the **Arrow up** icon and you are done.
