### ISSUE TITLE
Make recordings private

### ISSUE THREAD

**Issue by sulzer** [blindsidenetworks/moodle-mod_bigbluebuttonbn#308]
Hello there,

I've noticed in this FAQ that there's an option to make recording "private", meaning that it can only be accessed from within Moodle (lock icon):
https://support.blindsidenetworks.com/hc/en-us/articles/360017653572-How-do-I-control-visibility-access-to-recordings-

Was this functionality added recently?  I am using bigbluebuttonbn 2.3.1 and was not able to see this option.  Currently anyone who has the recording link can access the recording, which can lead to data privacy issues depending on the recorded content.  

The issue has been mentioned here but so far the available workarounds only seem to be for Greenlight:
https://docs.bigbluebutton.org/admin/privacy.html#all-recordings-are-always-accessible

Are there any plans to implement an access control functionality for recordings to the Moodle plugin?

Cheers,
Romeo

**Comment by jfederico** [comment]
Hi Romeo,

It has nothing to do with the Moodle plugin. It is a modification that has to be done in BBB itself.

The first document you are pointing at, refers to our own implementation of a recording server that is not only able to enhance security but also produce several formats and statistic reports.

There are several options in consideration but the bottom line is that there has to be a broker application handling the authorisation. 

One alternative is to do it through Scalelite (it is not implemented there either), another one is to extend Nginx with OpenResty.

Not a minor development though.
