### ISSUE TITLE
very very slow page because of slow queries and lack of limitation in select

### ISSUE THREAD

**Issue by emamirazavi** [blindsidenetworks/moodle-mod_bigbluebuttonbn#319]
Hello. Because of large log table with almost 671792 rows, in `/mod/bigbluebuttonbn/view.php?id=<ID>` page with 65 recorded sessions [we need surely paginator for listing published playbacks], we detect to need adding a new index for just two columns `userid` and `log`. This is vital for MySQL and PostgreSQL and tested for them successfully. We have some queries in the module like `SELECT id, meta FROM mdl_bigbluebuttonbn_logs WHERE userid = '7327' AND log = 'Join'  ORDER BY id ASC LIMIT 1, 18446744073709551615;`. These queries last many seconds to respond (3, 4, 5 or ... secs)! We must add some new indexes. Is there anybody to add the below index to deploying process of the module.

for example we've added this to solve the problem:

```
CREATE INDEX mdl_bigblogs_userlogs ON mdl_bigbluebuttonbn_logs (userid, log);
```

**Comment by prigaux** [comment]
Our mysqld CPU was stressed because the SQL request from PHP function `bigbluebuttonbn_user_complete` was not indexed.
Something like : `SELECT COUNT(*) FROM mdl_bigbluebuttonbn_logs WHERE courseid = '20182' AND bigbluebuttonbnid = '4227' AND userid = '284732' AND (log = 'Join' OR log = 'Played')`

An index on (courseid, bigbluebuttonbnid, userid, log) solved the issue.

I just tried with the index you suggest, and it solves the issue too!

**Comment by jfederico** [comment]
Thanks @prigaux for confirming the issue.

@emamirazavi can you pull this code and verify that solves your problem? https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/pull/327

If it does it will be part of the next release

**Comment by emamirazavi** [comment]
@prigaux many thanks for your feedback. This reported problem is not your problem. `SELECT id, meta FROM mdl_bigbluebuttonbn_logs WHERE userid = '7327' AND log = 'Join' ORDER BY id ASC LIMIT 1, 18446744073709551615;` does not need index on (courseid, bigbluebuttonbnid, userid, log) and this index is not useful index because of index rules in MySQL. It may this problem does not exist in PostgreSQL but in MySQL rules about indexing, we must add that index to make mentioned queries fast and keep it from being a dangerous query. Please see this important link about my view:

https://www.mysqltutorial.org/mysql-index/mysql-composite-index

A composite index is an index on multiple columns. MySQL allows you to create a composite index that consists of up to 16 columns.
A composite index is also known as a multiple-column index.
The query optimizer uses the composite indexes for queries that test all columns in the index, or queries that test the first columns, the first two columns, and so on.

I want to say indexing on 4 cols (courseid, bigbluebuttonbnid, userid, log) does help to search on userid, log! It wants other index to speed up and work.

**Comment by jfederico** [comment]
Thanks @emamirazavi since I did not receive response I merged it anyways. If you can please try from master

**Comment by emamirazavi** [comment]
Dear @jfederico , have you ever added my suggestion about these two columns index?

**Comment by jfederico** [comment]
Just scroll up, you will find what I wrote 

>Thanks @emamirazavi since I did not receive response I merged it anyways. If you can please try from master

Scroll up, there is what I asked first and did not get answer

>@emamirazavi can you pull this code and verify that solves your problem? #327

#327 is merged, I may be confused but that was what you asked, wasn't?

**Comment by emamirazavi** [comment]
@jfederico Excuse me, many many thanks for it. Okay, Got it.
