### ISSUE TITLE
Strings hard coded

### ISSUE THREAD

**Issue by ali-alhaidary** [blindsidenetworks/moodle-mod_bigbluebuttonbn#322]
Some strings are hard coded and can not be translated as they are not in the language pack.
![Screenshot_2021-01-07 the5stars - غرفة صوتية](https://user-images.githubusercontent.com/75235623/104162148-1cd19900-5405-11eb-809c-86fef0b8be7b.png)

**Comment by jfederico** [comment]
That is a BigBlueButton translation. You have to contribute that string on Transifex. Look for the bigbluebutton project there.

**Comment by ali-alhaidary** [comment]
can not be translated, it is hard coded and not in the language pack. I have already translated 70% of it to Arabic.

**Comment by jfederico** [comment]
I see. But still, it has nothing to do with the plugin. You can report the issue in transifex ot directly to the bigbluebutton/bigbluebutton on github repository.

**Comment by ali-alhaidary** [comment]
Thanks, I did to all parties that I know....

Ali
