### ISSUE TITLE
BBB-room does not automaticaly end when last moderator has left the room

### ISSUE THREAD

**Issue by andreasschenkel** [blindsidenetworks/moodle-mod_bigbluebuttonbn#323]
In room that was startet with the plugin the moderator left the room but still two user (withour moderator role) where in the room dows not stop after leafing the room. (Maybe it is related to the following: We have rooms with many duplicated users inside. So use A enters the room  5 or more times "automaticaly". So for a group with 20 Users the participant-list can have 60 or more users.)

**Comment by jfederico** [comment]
No, it is not related. That is how BBB works, as long as there is one user, the meetings stays open. In this case yout Teacher should end the meeting either on logout or from the activity in Moodle
