### ISSUE TITLE
duplicated users 

### ISSUE THREAD

**Issue by andreasschenkel** [blindsidenetworks/moodle-mod_bigbluebuttonbn#324]
We have rooms with many duplicated users inside. So use A enters the room  5 or more times "automatically". So for a group with 20 Users the participant-list can have 60 or more users.
User A
User A
User A
User A
User B
User C
User C
...

**Comment by jfederico** [comment]
It doesn't seem to be related to the plugin though.

I would bet this does not happen always, does it?

**Comment by jfederico** [comment]
I am going to close this one as it is not related to the plugin. More likely it is a race condition due an overhead of users that the server is not able to handle.
