### ISSUE TITLE
Unit test failures with latest upstream Moodle 3.9

### ISSUE THREAD

**Issue by danmarsden** [blindsidenetworks/moodle-mod_bigbluebuttonbn#345]
1) mod_bigbluebuttonbn_lib_testcase::test_mod_bigbluebuttonbn_core_calendar_provide_event_action
Failed asserting that core_calendar\local\event\value_objects\action Object &0000000034f725710000000065ce8f88 (
'name' => 'Join session'
'url' => moodle_url Object &0000000034f725350000000065ce8f88 (
'scheme' => 'https'
'host' => 'www.example.com'
'port' => ''
'user' => ''
'pass' => ''
'path' => '/moodle/mod/bigbluebuttonbn/bbb_view.php'
'slashargument' => ''
'anchor' => null
'params' => Array &0 (
'action' => 'join'
'id' => '117000'
'bn' => '317000'
'timeline' => '1'
)
)
'itemcount' => 1
'actionable' => true
) is null.

/var/www/html/mod/bigbluebuttonbn/tests/lib_test.php:712
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

This appears to be caused by the changes from this tracker issue which seems to have a regression:
https://tracker.moodle.org/browse/MDL-67494

But it also looks like we need to add:
$event->priority = CALENDAR_EVENT_USER_OVERRIDE_PRIORITY;
to the event in here:
https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/blob/master/tests/lib_test.php#L731

We'll do some more testing and push through a PR later tihs week unless someone beats us to it.

**Comment by laurentdavid** [comment]
Hi Dan,

I think the test will need to be adjusted to just test what is necessary in the return value and not all the fields if they are not important for this test. I can adjust this as I am currently working on the 2.5 (integration to core & refactor).

Laurent
