### ISSUE TITLE
all users enrolled can not be removed

### ISSUE THREAD

**Issue by andreasschenkel** [blindsidenetworks/moodle-mod_bigbluebuttonbn#349]
![bbb2](https://user-images.githubusercontent.com/31856043/110781354-16756700-8266-11eb-8a94-6413d4883375.png)
After upgrading the new BBB-Moodle-Pluign has not the feature to remove the
all users enrolled from the Assignation list .
So all users have access to the bbb-room.
In the previous version it was possible to remove this "all users enrolled" setting.

**Comment by jfederico** [comment]
Yeah, it does not make sense to remove the default. You can only set it up to All Viewers or All Moderators.

The normal case is, you define who will be moderator and everybody else will join as viewer.

But keep in mind that this is not for permissions. It is only for matching roles in both systems.
