### ISSUE TITLE
Notification Mail

### ISSUE THREAD

**Issue by LiohMoeller** [blindsidenetworks/moodle-mod_bigbluebuttonbn#389]
Within the Plugin configuration it states that in order to activate the mail recording notification, one has to enable post_publish_recording_ready_callback  on the BBB side.

Within our BBB (2.3) installation there is a script _/usr/local/bigbluebutton/core/scripts/post_publish/post_publish_recording_ready_callback.rb_ but I did not find any reference on how to activate this.

**Comment by jfederico** [comment]
It is activated by default. It should just work. Check the logs and see if BBB is attempting to perform the callback

In BBB execute
`sudo tail -f /var/log/bigbluebutton/post_publish.log`

That will show you the post_publish logs in particular. If you have an issue, it should be shown there.

**Comment by LiohMoeller** [comment]
Yes, it shows up there but still the notification mail is not sent. Should it be sent by Moodle (via the Plugin) or the BBB Server?
