### ISSUE TITLE
The presentation view button is not displayed in moodle 3.11

### ISSUE THREAD

**Issue by nikkei00** [blindsidenetworks/moodle-mod_bigbluebuttonbn#425]
The presentation view button is not displayed in moodle 3.11.

Users do not understand that it is necessary to click even on the non-clickable (not blue and not underlined, like the URL) word " presentation"
I suggest that there should be a full-fledged button: ![image](https://user-images.githubusercontent.com/64165027/128067557-f0bdd871-8cfc-4e45-a768-edf76bbe48c8.png)

![6041](https://user-images.githubusercontent.com/64165027/128067384-88422ab9-5f72-427c-b3b9-35c2b6964fcf.png)

**Comment by jfederico** [comment]
Requests regarding BBB itself should be opened either on the BBB repo or the dev mailing list.
