### ISSUE TITLE
Prevent the shared_secret setting from being observed when forced in config.php

### ISSUE THREAD

**Issue by nhoobin** [blindsidenetworks/moodle-mod_bigbluebuttonbn#459]
When the config setting is forced eg. `$CFG->bigbluebuttonbn_shared_secret = 'thesecret';` in config.php, it is possible to view this value on the settings page.

With the implementaion of https://tracker.moodle.org/browse/MDL-63734 in Moodle 3.9, if the setting was of type `admin_setting_configpasswordunmask` then the value would not be visible and will prevent leaking the secret.

**Comment by jfederico** [comment]
Addressed on 2.4 and 2.5
