### ISSUE TITLE
Getting error in dashboard:

### ISSUE THREAD

**Issue by maikoly1** [blindsidenetworks/moodle-mod_bigbluebuttonbn#535]
Exception - Call to a member function get_instance_var() on null
line 324 of /mod/bigbluebuttonbn/classes/local/proxy/bigbluebutton_proxy.php: Error thrown
line 499 of /mod/bigbluebuttonbn/lib.php: call to mod_bigbluebuttonbn\local\proxy\bigbluebutton_proxy::view_get_activity_status()
line 7925 of /lib/moodlelib.php: call to mod_bigbluebuttonbn_core_calendar_is_event_visible()
line 339 of /calendar/classes/local/event/container.php: call to component_callback()
line 54 of /calendar/classes/local/event/factories/event_factory.php: call to core_calendar\local\event\container::apply_component_is_event_visible()
line 205 of /calendar/classes/local/event/factories/event_abstract_factory.php: call to core_calendar\local\event\factories\event_factory->expose_event()
line 360 of /calendar/classes/local/event/data_access/event_vault.php: call to core_calendar\local\event\factories\event_abstract_factory->create_instance()
line 172 of /calendar/classes/local/event/data_access/event_vault.php: call to core_calendar\local\event\data_access\event_vault->transform_from_database_record()
line 95 of /calendar/classes/local/api.php: call to core_calendar\local\event\data_access\event_vault->get_events()
line 3506 of /calendar/lib.php: call to core_calendar\local\api::get_events()
line 57 of /blocks/calendar_month/block_calendar_month.php: call to calendar_get_view()
line 341 of /blocks/moodleblock.class.php: call to block_calendar_month->get_content()
line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 3966 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 40 of /theme/boost/layout/columns2.php: call to core_renderer->blocks()
line 1396 of /lib/outputrenderers.php: call to include()
line 1326 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 165 of /my/index.php: call to core_renderer->header()

**Comment by jfederico** [comment]
Thanks for the report, but you need to be more specific.

What are you trying to do? What version of Moodle and the plugin you have? How do you reproduce the problem?

The more information you provide the more likely someone will be able to help you.

Also, we don't use GitHub for tracking issues. You should open an issue in Moodle Tracking system following Moodle rules for reporting issues https://docs.moodle.org/dev/Tracker_introduction.
