### ISSUE TITLE
Want to rebuild JS files

### ISSUE THREAD

**Issue by ansari9546** [blindsidenetworks/moodle-mod_bigbluebuttonbn#539]
I want to build the YUI JS files again. But I am unable to find the script that could build the YUI JS files. Because I cannot find the script in the repo.

Specifications:-
- Moodle version 3.11
- BigBlueButton 2.4

**Comment by jfederico** [comment]
On 2.4 you can use [shifter](https://docs.moodle.org/dev/YUI/Shifter)
