### ISSUE TITLE
Option "Session can be recorded" strange behaviour

### ISSUE THREAD

**Issue by SebastianZiegler** [blindsidenetworks/moodle-mod_bigbluebuttonbn#548]
Hello,

one of our teachers recorded a session in BBB, the session shown up in the activity. Yesterday the recordings aren't visible anymore, because the teacher changed the setting for the activity and unmarked the option "Session can be recorded". It takes a while to find out why the recording aren't shown anymore.

I think the wording or functionallity is a bit confusing. I whould prefer, that this option, did not belongs to old recording and only stop to make new ones.  

Best regards
Sebastian

**Comment by ssj365** [comment]
Hi Sebastian, please could you confirm the BBB plugin version you are using is v2.4.5? We have identified the bug you're referring to in v2.4.5 and opened an issue for it here [CONTRIB-8917](https://tracker.moodle.org/browse/CONTRIB-8917) 

If you think you have found a bug in this plugin, please open a ticket in the [Bug Tracker](https://tracker.moodle.org/issues/?jql=project%20%3D%20CONTRIB%20AND%20component%20%3D%20%22Module%3A+BigBlueButtonBN%22) and provide details of how to reproduce the issue. The more details you provide the easier it is for us to find and solve the problem.

Thanks!

**Comment by SebastianZiegler** [comment]
Hi,

yes I checked in 2.4.4 and 2.4.5 same behaviour in both versions.

best regards

**Comment by jfederico** [comment]
Issue tracked in JIRA https://tracker.moodle.org/browse/CONTRIB-8917
