### ISSUE TITLE
After the last merges there is an error shown after saving changes to an instance

### ISSUE THREAD

**Issue by jfederico** [blindsidenetworks/moodle-mod_bigbluebuttonbn#96]
This is the error I am seeing:

![image](https://user-images.githubusercontent.com/578359/50251252-44361300-03b1-11e9-8bff-922c76b0a6a4.png)

I am opening this issue in Git as this is something that just came up in development

**Comment by kiklop74** [comment]
Are there any specific steps to reproduce this?

**Comment by jfederico** [comment]
No, I tried in two more instances I did not get any errors. 

As German pointed out, it may have been a corrupted database. Let's close it and wait to see if it comes up later on.
